// =============================================================================
// Kernel Zxyphor - Interrupt Descriptor Table (IDT)
// =============================================================================
// The IDT maps interrupt/exception vectors (0-255) to handler functions.
// x86_64 uses 64-bit interrupt gate descriptors. Each entry specifies:
//   - The handler function address (split across multiple fields)
//   - The code segment selector to use
//   - Stack table index (for IST — Interrupt Stack Table)
//   - Gate type and privilege level
//
// Vectors 0-31:  CPU exceptions (divide error, page fault, etc.)
// Vectors 32-47: IRQs (remapped from PIC default 0-15)
// Vector 128:    System call interrupt (0x80, legacy — we also use SYSCALL)
// =============================================================================

const main = @import("../main.zig");
const gdt = @import("gdt.zig");

// =============================================================================
// IDT constants
// =============================================================================
pub const IDT_ENTRIES: usize = 256;

// Gate types for 64-bit mode
const GATE_INTERRUPT: u4 = 0xE; // Interrupt gate — clears IF (disables interrupts)
const GATE_TRAP: u4 = 0xF; // Trap gate — does NOT clear IF

// DPL (Descriptor Privilege Level)
const DPL_KERNEL: u2 = 0;
const DPL_USER: u2 = 3;

// =============================================================================
// IDT Entry (16 bytes in 64-bit mode)
// =============================================================================
const IdtEntry = packed struct {
    offset_low: u16, // Handler address bits 0-15
    selector: u16, // Code segment selector (usually 0x08)
    ist: u3, // Interrupt Stack Table index (0 = don't switch)
    reserved0: u5, // Must be zero
    gate_type: u4, // Gate type (interrupt or trap)
    zero: u1, // Must be zero
    dpl: u2, // Minimum privilege level for software interrupt
    present: u1, // Must be 1 for valid entries
    offset_mid: u16, // Handler address bits 16-31
    offset_high: u32, // Handler address bits 32-63
    reserved1: u32, // Must be zero

    /// Create an IDT entry for a handler function
    pub fn create(handler: u64, selector: u16, ist_index: u3, gate_type: u4, dpl: u2) IdtEntry {
        return IdtEntry{
            .offset_low = @truncate(handler),
            .selector = selector,
            .ist = ist_index,
            .reserved0 = 0,
            .gate_type = gate_type,
            .zero = 0,
            .dpl = dpl,
            .present = 1,
            .offset_mid = @truncate(handler >> 16),
            .offset_high = @truncate(handler >> 32),
            .reserved1 = 0,
        };
    }

    /// Create a not-present (empty) IDT entry
    pub fn empty() IdtEntry {
        return IdtEntry{
            .offset_low = 0,
            .selector = 0,
            .ist = 0,
            .reserved0 = 0,
            .gate_type = 0,
            .zero = 0,
            .dpl = 0,
            .present = 0,
            .offset_mid = 0,
            .offset_high = 0,
            .reserved1 = 0,
        };
    }
};

// =============================================================================
// IDT Pointer (IDTR) — loaded with lidt instruction
// =============================================================================
const IdtPointer = packed struct {
    limit: u16,
    base: u64,
};

// =============================================================================
// IDT table and pointer
// =============================================================================
var idt_entries: [IDT_ENTRIES]IdtEntry align(16) = [_]IdtEntry{IdtEntry.empty()} ** IDT_ENTRIES;
var idt_pointer: IdtPointer = undefined;

// =============================================================================
// ISR stub type — generated by assembly macro
// =============================================================================
const IsrStub = *const fn () callconv(.Naked) void;

// =============================================================================
// Exception handler stubs (vectors 0-31)
// Each stub pushes an error code (or dummy), the vector number, and jumps
// to the common handler. Exceptions that push error codes: 8,10,11,12,13,14,17,21,29,30
// =============================================================================
fn makeIsrStub(comptime vector: u8, comptime has_error_code: bool) IsrStub {
    return struct {
        fn handler() callconv(.Naked) void {
            if (!has_error_code) {
                // Push a dummy error code so the stack frame is uniform
                asm volatile ("pushq $0");
            }
            // Push the interrupt vector number
            asm volatile ("pushq %[vec]"
                :
                : [vec] "i" (@as(u64, vector)),
            );
            // Jump to common handler
            asm volatile ("jmp isr_common_stub");
        }
    }.handler;
}

// CPU exception stubs (vectors 0-31)
const isr_stubs = blk: {
    var stubs: [32]IsrStub = undefined;
    // Vectors with error codes: 8, 10, 11, 12, 13, 14, 17, 21, 29, 30
    const error_code_vectors = [_]u8{ 8, 10, 11, 12, 13, 14, 17, 21, 29, 30 };

    for (0..32) |i| {
        var has_error = false;
        for (error_code_vectors) |ec| {
            if (i == ec) {
                has_error = true;
                break;
            }
        }
        stubs[i] = makeIsrStub(@intCast(i), has_error);
    }
    break :blk stubs;
};

// IRQ handler stubs (vectors 32-47)
fn makeIrqStub(comptime irq: u8) IsrStub {
    return makeIsrStub(32 + irq, false);
}

const irq_stubs = blk: {
    var stubs: [16]IsrStub = undefined;
    for (0..16) |i| {
        stubs[i] = makeIrqStub(@intCast(i));
    }
    break :blk stubs;
};

// =============================================================================
// Common ISR handler (called from assembly stubs)
// =============================================================================
// Stack frame when we arrive here:
//   [rsp+0]   : vector number
//   [rsp+8]   : error code (real or dummy 0)
//   [rsp+16]  : RIP (return address pushed by CPU)
//   [rsp+24]  : CS
//   [rsp+32]  : RFLAGS
//   [rsp+40]  : RSP (if privilege change)
//   [rsp+48]  : SS (if privilege change)
// =============================================================================
const InterruptFrame = extern struct {
    // Registers pushed by our common stub
    r15: u64,
    r14: u64,
    r13: u64,
    r12: u64,
    r11: u64,
    r10: u64,
    r9: u64,
    r8: u64,
    rbp: u64,
    rdi: u64,
    rsi: u64,
    rdx: u64,
    rcx: u64,
    rbx: u64,
    rax: u64,
    // Pushed by ISR stub
    vector: u64,
    error_code: u64,
    // Pushed by CPU on interrupt
    rip: u64,
    cs: u64,
    rflags: u64,
    rsp: u64,
    ss: u64,
};

/// Common assembly stub that saves registers and calls the Zig handler
export fn isr_common_stub() callconv(.Naked) void {
    // Save all general-purpose registers
    asm volatile (
        \\ pushq %%rax
        \\ pushq %%rbx
        \\ pushq %%rcx
        \\ pushq %%rdx
        \\ pushq %%rsi
        \\ pushq %%rdi
        \\ pushq %%rbp
        \\ pushq %%r8
        \\ pushq %%r9
        \\ pushq %%r10
        \\ pushq %%r11
        \\ pushq %%r12
        \\ pushq %%r13
        \\ pushq %%r14
        \\ pushq %%r15
        \\
        \\ movq %%rsp, %%rdi   // Pass frame pointer as first argument
        \\ call isrHandler      // Call the Zig handler
        \\
        \\ popq %%r15
        \\ popq %%r14
        \\ popq %%r13
        \\ popq %%r12
        \\ popq %%r11
        \\ popq %%r10
        \\ popq %%r9
        \\ popq %%r8
        \\ popq %%rbp
        \\ popq %%rdi
        \\ popq %%rsi
        \\ popq %%rdx
        \\ popq %%rcx
        \\ popq %%rbx
        \\ popq %%rax
        \\
        \\ addq $16, %%rsp     // Remove error code and vector number
        \\ iretq               // Return from interrupt
    );
}

// =============================================================================
// Exception names for human-readable error messages
// =============================================================================
const exception_names = [32][]const u8{
    "Division Error",
    "Debug",
    "Non-Maskable Interrupt",
    "Breakpoint",
    "Overflow",
    "Bound Range Exceeded",
    "Invalid Opcode",
    "Device Not Available",
    "Double Fault",
    "Coprocessor Segment Overrun",
    "Invalid TSS",
    "Segment Not Present",
    "Stack-Segment Fault",
    "General Protection Fault",
    "Page Fault",
    "Reserved",
    "x87 Floating-Point Exception",
    "Alignment Check",
    "Machine Check",
    "SIMD Floating-Point Exception",
    "Virtualization Exception",
    "Control Protection Exception",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Hypervisor Injection Exception",
    "VMM Communication Exception",
    "Security Exception",
    "Reserved",
};

// =============================================================================
// User-installable IRQ handlers
// =============================================================================
const IrqHandler = *const fn (u8) void;
var irq_handlers: [16]?IrqHandler = [_]?IrqHandler{null} ** 16;

/// Register a handler for a specific IRQ (0-15)
pub fn registerIrqHandler(irq: u8, handler: IrqHandler) void {
    if (irq < 16) {
        irq_handlers[irq] = handler;
        main.klog(.debug, "IDT: Registered handler for IRQ{d}", .{irq});
    }
}

/// Unregister a handler for a specific IRQ
pub fn unregisterIrqHandler(irq: u8) void {
    if (irq < 16) {
        irq_handlers[irq] = null;
    }
}

// =============================================================================
// Main interrupt/exception handler — called from assembly common stub
// =============================================================================
export fn isrHandler(frame: *InterruptFrame) void {
    const vector = frame.vector;

    if (vector < 32) {
        // CPU exception
        handleException(frame);
    } else if (vector >= 32 and vector < 48) {
        // Hardware IRQ (PIC IRQ 0-15)
        const irq: u8 = @truncate(vector - 32);
        handleIrq(irq, frame);
    } else if (vector == 0x80) {
        // Legacy system call (int 0x80)
        main.syscall_handler.handleLegacySyscall(frame);
    }
}

/// Handle a CPU exception
fn handleException(frame: *InterruptFrame) void {
    const vector: usize = @truncate(frame.vector);
    const name = if (vector < 32) exception_names[vector] else "Unknown";

    // Double fault and machine check are always fatal
    if (vector == 8 or vector == 18) {
        main.serial.writer().print("\r\nFATAL: {s} (vector {d})\r\n", .{ name, vector }) catch {};
        main.serial.writer().print("Error code: 0x{x}\r\n", .{frame.error_code}) catch {};
        main.serial.writer().print("RIP: 0x{x:0>16}\r\n", .{frame.rip}) catch {};
        main.serial.writer().print("RSP: 0x{x:0>16}\r\n", .{frame.rsp}) catch {};
        main.serial.writer().print("CR2: 0x{x:0>16}\r\n", .{main.registers.readCr2()}) catch {};
        @panic(name);
    }

    // Page fault needs special handling
    if (vector == 14) {
        handlePageFault(frame);
        return;
    }

    // General protection fault
    if (vector == 13) {
        main.serial.writer().print("\r\nGeneral Protection Fault!\r\n", .{}) catch {};
        main.serial.writer().print("Error code: 0x{x}\r\n", .{frame.error_code}) catch {};
        main.serial.writer().print("RIP: 0x{x:0>16}\r\n", .{frame.rip}) catch {};
        main.serial.writer().print("CS:  0x{x}\r\n", .{frame.cs}) catch {};

        // If it was in user mode, kill the process; otherwise panic
        if (frame.cs & 3 != 0) {
            main.klog(.err, "GPF in userspace at RIP=0x{x}, killing process", .{frame.rip});
            main.process.killCurrent(.segfault);
        } else {
            @panic("General Protection Fault in kernel mode");
        }
        return;
    }

    // Other exceptions — log and potentially kill the process
    main.klog(.err, "Exception: {s} (#{d}) at RIP=0x{x}", .{ name, vector, frame.rip });

    if (frame.cs & 3 != 0) {
        // Exception in user mode — kill the process
        main.process.killCurrent(.exception);
    } else {
        // Exception in kernel mode — this is bad
        @panic("Unhandled exception in kernel mode");
    }
}

/// Handle a page fault (vector 14)
fn handlePageFault(frame: *InterruptFrame) void {
    const fault_addr = main.registers.readCr2();
    const error_code = frame.error_code;

    // Decode page fault error code bits
    const present = (error_code & 1) != 0;
    const write = (error_code & 2) != 0;
    const user = (error_code & 4) != 0;
    const reserved_write = (error_code & 8) != 0;
    const instruction_fetch = (error_code & 16) != 0;

    main.klog(.debug, "Page fault at 0x{x:0>16}: present={} write={} user={} rsvd={} ifetch={}", .{
        fault_addr,
        present,
        write,
        user,
        reserved_write,
        instruction_fetch,
    });

    // Try to handle the page fault through the VMM (demand paging, COW, etc.)
    if (main.vmm.handlePageFault(fault_addr, error_code)) {
        return; // Handled successfully — page has been mapped
    }

    // Unresolvable page fault
    if (user) {
        main.klog(.err, "Segmentation fault: process accessed 0x{x}", .{fault_addr});
        main.process.killCurrent(.segfault);
    } else {
        main.serial.writer().print("\r\nKernel Page Fault!\r\n", .{}) catch {};
        main.serial.writer().print("Fault address: 0x{x:0>16}\r\n", .{fault_addr}) catch {};
        main.serial.writer().print("RIP: 0x{x:0>16}\r\n", .{frame.rip}) catch {};
        main.serial.writer().print("Error: P={} W={} U={}\r\n", .{ present, write, user }) catch {};
        @panic("Unresolvable page fault in kernel");
    }
}

/// Handle a hardware IRQ from the PIC
fn handleIrq(irq: u8, frame: *InterruptFrame) void {
    _ = frame;

    // Dispatch to registered handler
    if (irq < 16) {
        if (irq_handlers[irq]) |handler| {
            handler(irq);
        }
    }

    // Send End-of-Interrupt to PIC
    main.pic.sendEoi(irq);
}

// =============================================================================
// Initialize the IDT
// =============================================================================
pub fn initialize() void {
    // Install exception handlers (vectors 0-31)
    for (0..32) |i| {
        const handler_addr = @intFromPtr(isr_stubs[i]);
        const ist_index: u3 = if (i == 8) 1 else if (i == 2) 2 else 0;
        idt_entries[i] = IdtEntry.create(
            handler_addr,
            gdt.KERNEL_CODE_SELECTOR,
            ist_index,
            GATE_INTERRUPT,
            DPL_KERNEL,
        );
    }

    // Install IRQ handlers (vectors 32-47)
    for (0..16) |i| {
        const handler_addr = @intFromPtr(irq_stubs[i]);
        idt_entries[32 + i] = IdtEntry.create(
            handler_addr,
            gdt.KERNEL_CODE_SELECTOR,
            0,
            GATE_INTERRUPT,
            DPL_KERNEL,
        );
    }

    // Install syscall interrupt handler (vector 0x80) — accessible from ring 3
    idt_entries[0x80] = IdtEntry.create(
        @intFromPtr(makeIsrStub(0x80, false)),
        gdt.KERNEL_CODE_SELECTOR,
        0,
        GATE_TRAP, // Trap gate so interrupts stay enabled during syscall
        DPL_USER, // Callable from user mode
    );

    // Load the IDT
    idt_pointer = IdtPointer{
        .limit = @as(u16, @sizeOf(@TypeOf(idt_entries))) - 1,
        .base = @intFromPtr(&idt_entries),
    };

    asm volatile ("lidt (%[idt_ptr])"
        :
        : [idt_ptr] "r" (&idt_pointer),
        : "memory"
    );

    main.klog(.info, "IDT: Loaded with {d} entries", .{IDT_ENTRIES});
}

/// Set an IDT entry directly (for advanced use cases like APIC interrupts)
pub fn setEntry(vector: u8, handler_addr: u64, ist_index: u3, gate_type: u4, dpl: u2) void {
    idt_entries[vector] = IdtEntry.create(
        handler_addr,
        gdt.KERNEL_CODE_SELECTOR,
        ist_index,
        gate_type,
        dpl,
    );
}
