// Zxyphor Kernel - BPF Networking Programs,
// BPF kfuncs (kernel function calls),
// BPF Iterators, BPF Struct Ops,
// BPF LSM hooks, BPF cgroup, BPF sock_ops,
// BPF XDP metadata, BPF timer, BPF arena
//
// SPDX-License-Identifier: GPL-2.0 OR MIT

const std = @import("std");

// ============================================================================
// BPF Program Types (comprehensive)
// ============================================================================

pub const BpfProgType = enum(u32) {
    unspec = 0,
    socket_filter = 1,
    kprobe = 2,
    sched_cls = 3,
    sched_act = 4,
    tracepoint = 5,
    xdp = 6,
    perf_event = 7,
    cgroup_skb = 8,
    cgroup_sock = 9,
    lwt_in = 10,
    lwt_out = 11,
    lwt_xmit = 12,
    sock_ops = 13,
    sk_skb = 14,
    cgroup_device = 15,
    sk_msg = 16,
    raw_tracepoint = 17,
    cgroup_sock_addr = 18,
    lwt_seg6local = 19,
    lirc_mode2 = 20,
    sk_reuseport = 21,
    flow_dissector = 22,
    cgroup_sysctl = 23,
    raw_tracepoint_writable = 24,
    cgroup_sockopt = 25,
    tracing = 26,
    struct_ops = 27,
    ext = 28,
    lsm = 29,
    sk_lookup = 30,
    syscall = 31,
    netfilter = 32,
};

// ============================================================================
// BPF Attach Types (comprehensive)
// ============================================================================

pub const BpfAttachType = enum(u32) {
    cgroup_inet_ingress = 0,
    cgroup_inet_egress = 1,
    cgroup_inet_sock_create = 2,
    cgroup_sock_ops = 3,
    sk_skb_stream_parser = 4,
    sk_skb_stream_verdict = 5,
    cgroup_device = 6,
    sk_msg_verdict = 7,
    cgroup_inet4_bind = 8,
    cgroup_inet6_bind = 9,
    cgroup_inet4_connect = 10,
    cgroup_inet6_connect = 11,
    cgroup_inet4_post_bind = 12,
    cgroup_inet6_post_bind = 13,
    cgroup_udp4_sendmsg = 14,
    cgroup_udp6_sendmsg = 15,
    lirc_mode2 = 16,
    flow_dissector = 17,
    cgroup_sysctl = 18,
    cgroup_udp4_recvmsg = 19,
    cgroup_udp6_recvmsg = 20,
    cgroup_getsockopt = 21,
    cgroup_setsockopt = 22,
    trace_raw_tp = 23,
    trace_fentry = 24,
    trace_fexit = 25,
    modify_return = 26,
    lsm_mac = 27,
    trace_iter = 28,
    cgroup_inet4_getpeername = 29,
    cgroup_inet6_getpeername = 30,
    cgroup_inet4_getsockname = 31,
    cgroup_inet6_getsockname = 32,
    xdp_devmap = 33,
    cgroup_inet_sock_release = 34,
    xdp_cpumap = 35,
    sk_lookup = 36,
    xdp = 37,
    sk_skb_verdict = 38,
    sk_reuseport_select = 39,
    sk_reuseport_select_or_migrate = 40,
    perf_event = 41,
    trace_kprobe_multi = 42,
    lsm_cgroup = 43,
    struct_ops = 44,
    netfilter = 45,
    tcx_ingress = 46,
    tcx_egress = 47,
    trace_uprobe_multi = 48,
    cgroup_unix_connect = 49,
    cgroup_unix_sendmsg = 50,
    cgroup_unix_recvmsg = 51,
    cgroup_unix_getpeername = 52,
    cgroup_unix_getsockname = 53,
    netkit_primary = 54,
    netkit_peer = 55,
};

// ============================================================================
// BPF Map Types (comprehensive)
// ============================================================================

pub const BpfMapType = enum(u32) {
    unspec = 0,
    hash = 1,
    array = 2,
    prog_array = 3,
    perf_event_array = 4,
    percpu_hash = 5,
    percpu_array = 6,
    stack_trace = 7,
    cgroup_array = 8,
    lru_hash = 9,
    lru_percpu_hash = 10,
    lpm_trie = 11,
    array_of_maps = 12,
    hash_of_maps = 13,
    devmap = 14,
    sockmap = 15,
    cpumap = 16,
    xskmap = 17,
    sockhash = 18,
    cgroup_storage = 19,
    reuseport_sockarray = 20,
    percpu_cgroup_storage = 21,
    queue = 22,
    stack = 23,
    sk_storage = 24,
    devmap_hash = 25,
    struct_ops = 26,
    ringbuf = 27,
    inode_storage = 28,
    task_storage = 29,
    bloom_filter = 30,
    user_ringbuf = 31,
    cgrp_storage = 32,
    arena = 33,
};

// ============================================================================
// BPF Helper Function IDs
// ============================================================================

pub const BpfFunc = enum(u32) {
    unspec = 0,
    map_lookup_elem = 1,
    map_update_elem = 2,
    map_delete_elem = 3,
    probe_read = 4,
    ktime_get_ns = 5,
    trace_printk = 6,
    get_prandom_u32 = 7,
    get_smp_processor_id = 8,
    skb_store_bytes = 9,
    l3_csum_replace = 10,
    l4_csum_replace = 11,
    tail_call = 12,
    clone_redirect = 13,
    get_current_pid_tgid = 14,
    get_current_uid_gid = 15,
    get_current_comm = 16,
    get_cgroup_classid = 17,
    skb_vlan_push = 18,
    skb_vlan_pop = 19,
    skb_get_tunnel_key = 20,
    skb_set_tunnel_key = 21,
    perf_event_read = 22,
    redirect = 23,
    get_route_realm = 24,
    perf_event_output = 25,
    skb_load_bytes = 26,
    get_stackid = 27,
    csum_diff = 28,
    skb_get_tunnel_opt = 29,
    skb_set_tunnel_opt = 30,
    skb_change_proto = 31,
    skb_change_type = 32,
    skb_under_cgroup = 33,
    get_hash_recalc = 34,
    get_current_task = 35,
    probe_write_user = 36,
    current_task_under_cgroup = 37,
    skb_change_tail = 38,
    skb_pull_data = 39,
    csum_update = 40,
    set_hash_invalid = 41,
    get_numa_node_id = 42,
    skb_change_head = 43,
    xdp_adjust_head = 44,
    probe_read_str = 45,
    get_socket_cookie = 46,
    get_socket_uid = 47,
    set_hash = 48,
    setsockopt = 49,
    skb_adjust_room = 50,
    redirect_map = 51,
    sk_redirect_map = 52,
    sock_map_update = 53,
    xdp_adjust_meta = 54,
    perf_event_read_value = 55,
    perf_prog_read_value = 56,
    getsockopt = 57,
    override_return = 58,
    sock_ops_cb_flags_set = 59,
    msg_redirect_map = 60,
    msg_apply_bytes = 61,
    msg_cork_bytes = 62,
    msg_pull_data = 63,
    bind = 64,
    xdp_adjust_tail = 65,
    skb_get_xfrm_state = 66,
    get_stack = 67,
    skb_load_bytes_relative = 68,
    fib_lookup = 69,
    sock_hash_update = 70,
    msg_redirect_hash = 71,
    sk_redirect_hash = 72,
    lwt_push_encap = 73,
    lwt_seg6_store_bytes = 74,
    lwt_seg6_adjust_srh = 75,
    lwt_seg6_action = 76,
    rc_repeat = 77,
    rc_keydown = 78,
    skb_cgroup_id = 79,
    get_current_cgroup_id = 80,
    get_local_storage = 81,
    sk_select_reuseport = 82,
    skb_ancestor_cgroup_id = 83,
    sk_lookup_tcp = 84,
    sk_lookup_udp = 85,
    sk_release = 86,
    map_push_elem = 87,
    map_pop_elem = 88,
    map_peek_elem = 89,
    msg_push_data = 90,
    msg_pop_data = 91,
    rc_pointer_rel = 92,
    spin_lock = 93,
    spin_unlock = 94,
    sk_fullsock = 95,
    tcp_sock = 96,
    skb_ecn_set_ce = 97,
    get_listener_sock = 98,
    skc_lookup_tcp = 99,
    tcp_check_syncookie = 100,
    sysctl_get_name = 101,
    sysctl_get_current_value = 102,
    sysctl_get_new_value = 103,
    sysctl_set_new_value = 104,
    strtol = 105,
    strtoul = 106,
    sk_storage_get = 107,
    sk_storage_delete = 108,
    send_signal = 109,
    tcp_gen_syncookie = 110,
    skb_output = 111,
    probe_read_user = 112,
    probe_read_kernel = 113,
    probe_read_user_str = 114,
    probe_read_kernel_str = 115,
    tcp_send_ack = 116,
    send_signal_thread = 117,
    jiffies64 = 118,
    read_branch_records = 119,
    get_ns_current_pid_tgid = 120,
    xdp_output = 121,
    get_netns_cookie = 122,
    get_current_ancestor_cgroup_id = 123,
    sk_assign = 124,
    ktime_get_boot_ns = 125,
    seq_printf = 126,
    seq_write = 127,
    sk_cgroup_id = 128,
    sk_ancestor_cgroup_id = 129,
    ringbuf_output = 130,
    ringbuf_reserve = 131,
    ringbuf_submit = 132,
    ringbuf_discard = 133,
    ringbuf_query = 134,
    csum_level = 135,
    skc_to_tcp6_sock = 136,
    skc_to_tcp_sock = 137,
    skc_to_tcp_timewait_sock = 138,
    skc_to_tcp_request_sock = 139,
    skc_to_udp6_sock = 140,
    get_task_stack = 141,
    load_hdr_opt = 142,
    store_hdr_opt = 143,
    reserve_hdr_opt = 144,
    inode_storage_get = 145,
    inode_storage_delete = 146,
    d_path = 147,
    copy_from_user = 148,
    snprintf_btf = 149,
    seq_printf_btf = 150,
    skb_cgroup_classid = 151,
    redirect_neigh = 152,
    per_cpu_ptr = 153,
    this_cpu_ptr = 154,
    redirect_peer = 155,
    task_storage_get = 156,
    task_storage_delete = 157,
    get_current_task_btf = 158,
    bprm_opts_set = 159,
    ktime_get_coarse_ns = 160,
    ima_inode_hash = 161,
    sock_from_file = 162,
    check_mtu = 163,
    for_each_map_elem = 164,
    snprintf = 165,
    sys_bpf = 166,
    btf_find_by_name_kind = 167,
    sys_close = 168,
    timer_init = 169,
    timer_set_callback = 170,
    timer_start = 171,
    timer_cancel = 172,
    get_func_ip = 173,
    get_attach_cookie = 174,
    task_pt_regs = 175,
    get_branch_snapshot = 176,
    trace_vprintk = 177,
    skc_to_unix_sock = 178,
    kallsyms_lookup_name = 179,
    find_vma = 180,
    loop = 181,
    strncmp = 182,
    get_func_arg = 183,
    get_func_ret = 184,
    get_func_arg_cnt = 185,
    get_retval = 186,
    set_retval = 187,
    xdp_get_buff_len = 188,
    xdp_load_bytes = 189,
    xdp_store_bytes = 190,
    copy_from_user_task = 191,
    skb_set_tstamp = 192,
    ima_file_hash = 193,
    kptr_xchg = 194,
    map_lookup_percpu_elem = 195,
    skc_to_mptcp_sock = 196,
    dynptr_from_mem = 197,
    ringbuf_reserve_dynptr = 198,
    ringbuf_submit_dynptr = 199,
    ringbuf_discard_dynptr = 200,
    dynptr_read = 201,
    dynptr_write = 202,
    dynptr_data = 203,
    tcp_raw_gen_syncookie_ipv4 = 204,
    tcp_raw_gen_syncookie_ipv6 = 205,
    tcp_raw_check_syncookie_ipv4 = 206,
    tcp_raw_check_syncookie_ipv6 = 207,
    ktime_get_tai_ns = 208,
    user_ringbuf_drain = 209,
    cgrp_storage_get = 210,
    cgrp_storage_delete = 211,
};

// ============================================================================
// BPF kfunc (kernel function) Categories
// ============================================================================

pub const BpfKfuncSet = enum(u8) {
    set_any = 0,
    set_ret_null = 1,
    set_acquire = 2,
    set_release = 3,
    set_sleepable = 4,
    set_destructor = 5,
    set_trusted_args = 6,
    set_rcu = 7,
    set_rcu_protected = 8,
    set_iter = 9,
};

pub const BpfKfuncFlags = packed struct(u32) {
    ret_null: bool = false,
    kfunc_acquire: bool = false,
    kfunc_release: bool = false,
    kfunc_destructive: bool = false,
    kfunc_sleepable: bool = false,
    kfunc_trusted_args: bool = false,
    kfunc_rcu: bool = false,
    kfunc_rcu_protected: bool = false,
    _reserved: u24 = 0,
};

// ============================================================================
// BPF sock_ops callback operations
// ============================================================================

pub const BpfSockOpsOp = enum(u32) {
    void = 0,
    timeout_init = 1,           // TCP timeout init
    rwnd_init = 2,              // initial advertised window
    tcp_connect_cb = 3,         // called on connect()
    active_established_cb = 4,  // active connection established
    passive_established_cb = 5, // passive connection established
    needs_ecn = 6,              // needs ECN
    base_rtt = 7,               // base RTT
    rto_cb = 8,                 // RTO callback
    retrans_cb = 9,             // retransmission
    state_cb = 10,              // state change
    tcp_listen_cb = 11,         // listen()
    rtt_cb = 12,                // RTT measurement
    parse_hdr_opt_cb = 13,      // parse header options
    hdr_opt_len_cb = 14,        // header options length
    write_hdr_opt_cb = 15,      // write header options
};

pub const BpfSockOpsCbFlags = packed struct(u32) {
    bpf_sock_ops_rto_cb_flag: bool = false,
    bpf_sock_ops_retrans_cb_flag: bool = false,
    bpf_sock_ops_state_cb_flag: bool = false,
    bpf_sock_ops_rtt_cb_flag: bool = false,
    bpf_sock_ops_parse_all_hdr_opt: bool = false,
    bpf_sock_ops_parse_unknown_hdr_opt: bool = false,
    bpf_sock_ops_write_hdr_opt: bool = false,
    _reserved: u25 = 0,
};

// ============================================================================
// BPF Iterator Types
// ============================================================================

pub const BpfIterType = enum(u8) {
    task = 0,
    task_file = 1,
    task_vma = 2,
    bpf_map = 3,
    bpf_map_elem = 4,
    bpf_prog = 5,
    bpf_link = 6,
    tcp = 7,
    udp = 8,
    unix_sock = 9,
    netlink = 10,
    xdp_devmap = 11,
    ksym = 12,
    cgroup = 13,
};

pub const BpfIterInfo = struct {
    iter_type: BpfIterType,
    prog_fd: i32,
    target_fd: i32,
    flags: u32,
    seq_info: ?*anyopaque,
};

// ============================================================================
// BPF Struct Ops
// ============================================================================

pub const BpfStructOpsType = enum(u8) {
    tcp_congestion_ops = 0,
    bpf_dummy_ops = 1,
    sched_ext_ops = 2,
    bpf_struct_ops_tcp_ca = 3,
};

pub const BpfStructOpsState = enum(u8) {
    init = 0,
    inuse = 1,
    tobefree = 2,
    ready = 3,
};

// ============================================================================
// BPF LSM Hooks
// ============================================================================

pub const BpfLsmHook = enum(u16) {
    binder_set_context_mgr = 0,
    binder_transaction = 1,
    binder_transfer_binder = 2,
    binder_transfer_file = 3,
    ptrace_access_check = 4,
    ptrace_traceme = 5,
    capget = 6,
    capset = 7,
    capable = 8,
    quotactl = 9,
    quota_on = 10,
    syslog = 11,
    settime = 12,
    vm_enough_memory = 13,
    bprm_creds_for_exec = 14,
    bprm_creds_from_file = 15,
    bprm_check_security = 16,
    bprm_committing_creds = 17,
    bprm_committed_creds = 18,
    fs_context_dup = 19,
    fs_context_parse_param = 20,
    sb_alloc_security = 21,
    sb_free_security = 22,
    sb_delete = 23,
    sb_free_mnt_opts = 24,
    sb_eat_lsm_opts = 25,
    sb_mnt_opts_compat = 26,
    sb_remount = 27,
    sb_kern_mount = 28,
    sb_show_options = 29,
    sb_statfs = 30,
    sb_mount = 31,
    sb_umount = 32,
    sb_pivotroot = 33,
    sb_set_mnt_opts = 34,
    sb_clone_mnt_opts = 35,
    move_mount = 36,
    dentry_init_security = 37,
    dentry_create_files_as = 38,
    inode_alloc_security = 39,
    inode_free_security = 40,
    inode_init_security = 41,
    inode_init_security_anon = 42,
    inode_create = 43,
    inode_link = 44,
    inode_unlink = 45,
    inode_symlink = 46,
    inode_mkdir = 47,
    inode_rmdir = 48,
    inode_mknod = 49,
    inode_rename = 50,
    inode_readlink = 51,
    inode_follow_link = 52,
    inode_permission = 53,
    inode_setattr = 54,
    inode_getattr = 55,
    inode_setxattr = 56,
    inode_post_setxattr = 57,
    inode_getxattr = 58,
    inode_listxattr = 59,
    inode_removexattr = 60,
    inode_set_acl = 61,
    inode_get_acl = 62,
    inode_remove_acl = 63,
    file_permission = 64,
    file_alloc_security = 65,
    file_free_security = 66,
    file_ioctl = 67,
    file_ioctl_compat = 68,
    mmap_addr = 69,
    mmap_file = 70,
    file_mprotect = 71,
    file_lock = 72,
    file_fcntl = 73,
    file_set_fowner = 74,
    file_send_sigiotask = 75,
    file_receive = 76,
    file_open = 77,
    file_truncate = 78,
    task_alloc = 79,
    task_free = 80,
    cred_alloc_blank = 81,
    cred_free = 82,
    cred_prepare = 83,
    cred_transfer = 84,
    cred_getsecid = 85,
    kernel_act_as = 86,
    kernel_create_files_as = 87,
    kernel_module_request = 88,
    kernel_read_file = 89,
    kernel_post_read_file = 90,
    kernel_load_data = 91,
    kernel_post_load_data = 92,
    task_fix_setuid = 93,
    task_fix_setgid = 94,
    task_fix_setgroups = 95,
    task_setpgid = 96,
    task_getpgid = 97,
    task_getsid = 98,
    current_getsecid_subj = 99,
    task_getsecid_obj = 100,
    task_setnice = 101,
    task_setioprio = 102,
    task_getioprio = 103,
    task_prlimit = 104,
    task_setrlimit = 105,
    task_setscheduler = 106,
    task_getscheduler = 107,
    task_movememory = 108,
    task_kill = 109,
    task_prctl = 110,
    task_to_inode = 111,
    userns_create = 112,
    ipc_permission = 113,
    ipc_getsecid = 114,
    socket_create = 115,
    socket_post_create = 116,
    socket_socketpair = 117,
    socket_bind = 118,
    socket_connect = 119,
    socket_listen = 120,
    socket_accept = 121,
    socket_sendmsg = 122,
    socket_recvmsg = 123,
    socket_getsockname = 124,
    socket_getpeername = 125,
    socket_getsockopt = 126,
    socket_setsockopt = 127,
    socket_shutdown = 128,
    socket_sock_rcv_skb = 129,
    sk_alloc_security = 130,
    sk_free_security = 131,
    // (truncated for space, 200+ hooks total)
};

// ============================================================================
// BPF Link Types
// ============================================================================

pub const BpfLinkType = enum(u32) {
    unspec = 0,
    raw_tracepoint = 1,
    tracing = 2,
    cgroup = 3,
    iter = 4,
    netns = 5,
    xdp = 6,
    perf_event = 7,
    kprobe_multi = 8,
    struct_ops = 9,
    netfilter = 10,
    tcx = 11,
    uprobe_multi = 12,
    netkit = 13,
};

// ============================================================================
// BPF Arena
// ============================================================================

pub const BpfArenaFlags = packed struct(u32) {
    bpf_f_segv_on_fault: bool = false,
    bpf_f_no_user_conv: bool = false,
    _reserved: u30 = 0,
};

// ============================================================================
// BPF Timer
// ============================================================================

pub const BpfTimerFlags = packed struct(u32) {
    bpf_f_timer_abs: bool = false,
    bpf_f_timer_cpu_pin: bool = false,
    _reserved: u30 = 0,
};

// ============================================================================
// BPF Subsystem Manager
// ============================================================================

pub const BpfSubsystemManager = struct {
    loaded_progs: u32,
    loaded_maps: u32,
    attached_links: u32,
    jit_enabled: bool,
    jit_harden: u8,
    unprivileged_disabled: bool,
    kfunc_count: u32,
    struct_ops_count: u32,
    arena_enabled: bool,
    initialized: bool,

    pub fn init() BpfSubsystemManager {
        return std.mem.zeroes(BpfSubsystemManager);
    }
};
