// SPDX-License-Identifier: GPL-2.0
// Zxyphor Kernel - BPF Helper Functions, Program Types, Link Types
// Complete BPF helper definitions, prog type capabilities,
// BPF link, perf event integration, BPF LSM, BPF timer, kptr

const std = @import("std");

// ============================================================================
// BPF Program Types
// ============================================================================

pub const BpfProgType = enum(u32) {
    SocketFilter = 1,
    KProbe = 2,
    SchedCls = 3,
    SchedAct = 4,
    Tracepoint = 5,
    Xdp = 6,
    PerfEvent = 7,
    CgroupSkb = 8,
    CgroupSock = 9,
    LwtIn = 10,
    LwtOut = 11,
    LwtXmit = 12,
    SockOps = 13,
    SkSkb = 14,
    CgroupDevice = 15,
    SkMsg = 16,
    RawTracepoint = 17,
    CgroupSockAddr = 18,
    LwtSeg6local = 19,
    LircMode2 = 20,
    SkReuseport = 21,
    FlowDissector = 22,
    CgroupSysctl = 23,
    RawTracepointWritable = 24,
    CgroupSockopt = 25,
    Tracing = 26,
    StructOps = 27,
    Ext = 28,
    Lsm = 29,
    SkLookup = 30,
    Syscall = 31,
    Netfilter = 32,
};

// ============================================================================
// BPF Attach Types
// ============================================================================

pub const BpfAttachType = enum(u32) {
    CgroupInetIngress = 0,
    CgroupInetEgress = 1,
    CgroupInetSockCreate = 2,
    CgroupSockOps = 3,
    SkSkbStreamParser = 4,
    SkSkbStreamVerdict = 5,
    CgroupDevice = 6,
    SkMsgVerdict = 7,
    CgroupInet4Bind = 8,
    CgroupInet6Bind = 9,
    CgroupInet4Connect = 10,
    CgroupInet6Connect = 11,
    CgroupInet4PostBind = 12,
    CgroupInet6PostBind = 13,
    CgroupUdp4Sendmsg = 14,
    CgroupUdp6Sendmsg = 15,
    LircMode2 = 16,
    FlowDissector = 17,
    CgroupSysctl = 18,
    CgroupUdp4Recvmsg = 19,
    CgroupUdp6Recvmsg = 20,
    CgroupGetsockopt = 21,
    CgroupSetsockopt = 22,
    TraceRawTp = 23,
    TraceFentry = 24,
    TraceFexit = 25,
    ModifyReturn = 26,
    LsmMac = 27,
    TraceIter = 28,
    CgroupInet4Getpeername = 29,
    CgroupInet6Getpeername = 30,
    CgroupInet4Getsockname = 31,
    CgroupInet6Getsockname = 32,
    XdpDevmap = 33,
    CgroupInetSockRelease = 34,
    XdpCpumap = 35,
    SkLookup = 36,
    Xdp = 37,
    SkSkbVerdict = 38,
    SkReuseportSelect = 39,
    SkReuseportSelectOrMigrate = 40,
    PerfEvent = 41,
    TraceKprobeMulti = 42,
    LsmCgroup = 43,
    StructOps = 44,
    Netfilter = 45,
    TcxIngress = 46,
    TcxEgress = 47,
    TraceUprobeMulti = 48,
    NetkitPrimary = 49,
    NetkitPeer = 50,
};

// ============================================================================
// BPF Link Types
// ============================================================================

pub const BpfLinkType = enum(u32) {
    Unset = 0,
    RawTracepoint = 1,
    Tracing = 2,
    Cgroup = 3,
    Iter = 4,
    NetNs = 5,
    XDP = 6,
    PerfEvent = 7,
    KprobeMulti = 8,
    StructOps = 9,
    Netfilter = 10,
    TcxIngress = 11,
    TcxEgress = 12,
    UprobeMulti = 13,
    NetkitPrimary = 14,
    NetkitPeer = 15,
};

pub const BpfLink = struct {
    link_type: BpfLinkType,
    id: u32,
    prog_id: u32,
    prog_type: BpfProgType,
    attach_type: BpfAttachType,
};

// ============================================================================
// BPF Helper Functions
// ============================================================================

pub const BpfHelperFunc = enum(u32) {
    Unspec = 0,
    MapLookupElem = 1,
    MapUpdateElem = 2,
    MapDeleteElem = 3,
    ProbeRead = 4,
    KtimeGetNs = 5,
    TracePrintk = 6,
    GetPrandomU32 = 7,
    GetSmpProcessorId = 8,
    SkbStoreBytes = 9,
    L3CsumReplace = 10,
    L4CsumReplace = 11,
    TailCall = 12,
    CloneRedirect = 13,
    GetCurrentPidTgid = 14,
    GetCurrentUidGid = 15,
    GetCurrentComm = 16,
    GetCgroupClassid = 17,
    SkbVlanPush = 18,
    SkbVlanPop = 19,
    SkbGetTunnelKey = 20,
    SkbSetTunnelKey = 21,
    PerfEventRead = 22,
    Redirect = 23,
    GetRouteRealm = 24,
    PerfEventOutput = 25,
    SkbLoadBytes = 26,
    GetStackid = 27,
    CsumDiff = 28,
    SkbGetTunnelOpt = 29,
    SkbSetTunnelOpt = 30,
    SkbChangeProto = 31,
    SkbChangeType = 32,
    SkbUnderCgroup = 33,
    GetHashRecalc = 34,
    GetCurrentTask = 35,
    ProbeWriteUser = 36,
    CurrentTaskUnderCgroup = 37,
    SkbChangeTail = 38,
    SkbPullData = 39,
    CsumUpdate = 40,
    SetHashInvalid = 41,
    GetNumaNodeId = 42,
    SkbChangeHead = 43,
    XdpAdjustHead = 44,
    ProbeReadStr = 45,
    GetSocketCookie = 46,
    GetSocketUid = 47,
    SetHash = 48,
    Setsockopt = 49,
    SkbAdjustRoom = 50,
    RedirectMap = 51,
    SkRedirectMap = 52,
    SockMapUpdate = 53,
    XdpAdjustMeta = 54,
    PerfEventReadValue = 55,
    PerfProgReadValue = 56,
    Getsockopt = 57,
    OverrideReturn = 58,
    SockOpsCbFlagsSet = 59,
    MsgRedirectMap = 60,
    MsgApplyBytes = 61,
    MsgCorkBytes = 62,
    MsgPullData = 63,
    Bind = 64,
    XdpAdjustTail = 65,
    SkbGetXfrmState = 66,
    GetStack = 67,
    SkbLoadBytesRelative = 68,
    FibLookup = 69,
    SockHashUpdate = 70,
    MsgRedirectHash = 71,
    SkRedirectHash = 72,
    LwtPushEncap = 73,
    LwtSeg6StoreBytes = 74,
    LwtSeg6AdjustSrh = 75,
    LwtSeg6Action = 76,
    RcRepeat = 77,
    RcKeydown = 78,
    SkbCgroupId = 79,
    GetCurrentCgroupId = 80,
    GetLocalStorage = 81,
    SkSelectReuseport = 82,
    SkbAncestorCgroupId = 83,
    SkLookupTcp = 84,
    SkLookupUdp = 85,
    SkRelease = 86,
    MapPushElem = 87,
    MapPopElem = 88,
    MapPeekElem = 89,
    MsgPushData = 90,
    MsgPopData = 91,
    RcPointerRel = 92,
    SpinLock = 93,
    SpinUnlock = 94,
    SkFullsock = 95,
    TcpSock = 96,
    SkbEcnSetCe = 97,
    GetListenerSock = 98,
    SkbCgroupClassid = 99,
    // ...continued
    SkbCkVnetHdr = 100,
    SkbSetHdr = 101,
    ProbeReadKernel = 113,
    ProbeReadUser = 114,
    ProbeReadKernelStr = 115,
    ProbeReadUserStr = 116,
    TcpSendAck = 117,
    SendSignal = 118,
    TcpGenSynCookie = 119,
    Skc_lookup_tcp = 120,
    TcpCheckSynCookie = 121,
    SysctlGetName = 122,
    SysctlGetCurrentValue = 123,
    SysctlGetNewValue = 124,
    SysctlSetNewValue = 125,
    Strtol = 126,
    Strtoul = 127,
    SkStorageGet = 128,
    SkStorageDelete = 129,
    SendSignalThread = 130,
    JiffiesTo64 = 131,
    ReadBranchRecords = 132,
    GetNsCurrentPidTgid = 133,
    XdpOutputRelative = 134,
    GetNettoCgroupV2 = 135,
    SkAssign = 136,
    KtimeGetBootNs = 137,
    SeqPrintf = 138,
    SeqWrite = 139,
    SkCgroupId = 140,
    SkAncestorCgroupId = 141,
    RingbufOutput = 142,
    RingbufReserve = 143,
    RingbufSubmit = 144,
    RingbufDiscard = 145,
    RingbufQuery = 146,
    CsumLevel = 147,
    SkbSetCkVnetHdr = 148,
    TaskStorageGet = 149,
    TaskStorageDelete = 150,
    GetCurrentTaskBtfId = 151,
    BprmOptsSet = 152,
    KtimeGetCoarseNs = 153,
    ImaInodeHash = 154,
    SockFromFile = 155,
    CheckMtu = 156,
    ForEachMapElem = 157,
    Snprintf = 158,
    SysBpf = 159,
    SysClose = 160,
    TimerInit = 161,
    TimerSetCallback = 162,
    TimerStart = 163,
    TimerCancel = 164,
    GetFuncIp = 165,
    GetAttachCookie = 166,
    TaskPtRegs = 167,
    GetBranchSnapshot = 168,
    TraceVprintk = 169,
    CgrpStorageGet = 170,
    CgrpStorageDelete = 171,
    DynptrFromMem = 172,
    DynptrRead = 173,
    DynptrWrite = 174,
    DynptrData = 175,
    TcpRawGenSyncookieIpv4 = 176,
    TcpRawGenSyncookieIpv6 = 177,
    TcpRawCheckSyncookieIpv4 = 178,
    TcpRawCheckSyncookieIpv6 = 179,
    KtimeGetTaiNs = 180,
    UserRingbufDrain = 181,
    CgrpAncestorCgroupId = 182,
};

// ============================================================================
// BPF Commands (for bpf() syscall)
// ============================================================================

pub const BpfCmd = enum(u32) {
    MapCreate = 0,
    MapLookupElem = 1,
    MapUpdateElem = 2,
    MapDeleteElem = 3,
    MapGetNextKey = 4,
    ProgLoad = 5,
    ObjPin = 6,
    ObjGet = 7,
    ProgAttach = 8,
    ProgDetach = 9,
    ProgTaskFdQuery = 10,
    ProgGetNextId = 11,
    MapGetNextId = 12,
    ProgGetFdById = 13,
    MapGetFdById = 14,
    ObjGetInfoByFd = 15,
    ProgQuery = 16,
    RawTracepointOpen = 17,
    BtfLoad = 18,
    BtfGetFdById = 19,
    TaskFdQuery = 20,
    MapLookupAndDeleteElem = 21,
    MapFreeze = 22,
    BtfGetNextId = 23,
    MapLookupBatch = 24,
    MapLookupAndDeleteBatch = 25,
    MapUpdateBatch = 26,
    MapDeleteBatch = 27,
    LinkCreate = 28,
    LinkUpdate = 29,
    LinkGetFdById = 30,
    LinkGetNextId = 31,
    EnableStats = 32,
    IterCreate = 33,
    LinkDetach = 34,
    ProgBindMap = 35,
    TokenCreate = 36,
};

// ============================================================================
// BPF Timer / Kptr / Arena
// ============================================================================

pub const BpfTimerState = enum(u8) {
    Uninit = 0,
    Init = 1,
    CallbackSet = 2,
    Started = 3,
    Cancelled = 4,
};

pub const BpfTimer = struct {
    state: BpfTimerState,
    flags: u64,
    callback: u64,      // function pointer in BPF prog
    value: u64,
    expire_ns: u64,
};

pub const BpfKptrType = enum(u8) {
    Untrusted = 0,
    Ref = 1,
    Percpu = 2,
};

pub const BpfKptr = struct {
    kptr_type: BpfKptrType,
    btf_id: u32,
    offset: u32,
    ptr: u64,
};

pub const BpfArena = struct {
    user_vm_start: u64,
    user_vm_end: u64,
    kern_vm_start: u64,
    kern_vm_end: u64,
    map_fd: i32,
};

// ============================================================================
// BPF LSM Hooks
// ============================================================================

pub const BpfLsmHook = enum(u8) {
    BprmCheckSecurity = 0,
    FilePermission = 1,
    FileOpen = 2,
    FileIoctl = 3,
    MmapFile = 4,
    MmapAddr = 5,
    TaskCreate = 6,
    TaskFree = 7,
    TaskSetscheduler = 8,
    InodeMknod = 9,
    InodeCreate = 10,
    InodeLink = 11,
    InodeUnlink = 12,
    InodeSymlink = 13,
    InodeMkdir = 14,
    InodeRmdir = 15,
    InodeRename = 16,
    InodeReadlink = 17,
    InodeFollowLink = 18,
    InodePermission = 19,
    InodeSetattr = 20,
    InodeGetattr = 21,
    InodeSetxattr = 22,
    InodeGetxattr = 23,
    InodeListxattr = 24,
    InodeRemovexattr = 25,
    PathTruncate = 26,
    PathChmod = 27,
    PathChown = 28,
    SocketCreate = 29,
    SocketBind = 30,
    SocketConnect = 31,
    SocketListen = 32,
    SocketAccept = 33,
    SocketSendmsg = 34,
    SocketRecvmsg = 35,
    SkAlloc = 36,
    SkFree = 37,
};

// ============================================================================
// BPF Subsystem Manager
// ============================================================================

pub const BpfSubsystemManager = struct {
    total_progs: u32,
    total_maps: u32,
    total_links: u32,
    total_btf_objects: u32,
    jit_enabled: bool,
    jit_harden: u8,
    jit_kallsyms: bool,
    jit_limit: u64,
    unprivileged_bpf_disabled: u8,
    stats_enabled: bool,
    total_helper_calls: u64,
    total_map_ops: u64,
    total_verifier_passes: u64,
    total_ringbuf_output: u64,
    prog_type_counts: [33]u32,
    initialized: bool,

    pub fn init() BpfSubsystemManager {
        return .{
            .total_progs = 0,
            .total_maps = 0,
            .total_links = 0,
            .total_btf_objects = 0,
            .jit_enabled = true,
            .jit_harden = 0,
            .jit_kallsyms = true,
            .jit_limit = 0,
            .unprivileged_bpf_disabled = 2,
            .stats_enabled = false,
            .total_helper_calls = 0,
            .total_map_ops = 0,
            .total_verifier_passes = 0,
            .total_ringbuf_output = 0,
            .prog_type_counts = [_]u32{0} ** 33,
            .initialized = true,
        };
    }
};
